version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # explicitly mention backend Dockerfile
    image: discreta_gamified_learning
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile  # explicitly mention frontend Dockerfile inside ./src
    image: discreta_frontend
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
