version: '3'
services:
  app:
    build: .
    ports:
      - "5000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/discreta

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
